<?xml version="1.0"?>
<package format="3">
  <name>patrol_bringup</name>
  <version>0.0.1</version>
  <description>Launch files for the patrol system</description>

  <maintainer email="nvidia@example.com">nvidia</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <exec_depend>patrol_localization</exec_depend>
  <exec_depend>patrol_route_recorder</exec_depend>
  <exec_depend>patrol_entry_planner</exec_depend>
  <exec_depend>patrol_entry_executor</exec_depend>
  <exec_depend>patrol_route_follower</exec_depend>
  <exec_depend>patrol_auto_command_mux</exec_depend>
  <exec_depend>patrol_command_manager</exec_depend>
  <exec_depend>patrol_mission_manager</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
